# Generated by Django 4.1.3 on 2022-11-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_tracklikes_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
