# Generated by Django 4.1.3 on 2022-11-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_tracklikes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='servings',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
