# Generated by Django 4.1.3 on 2022-11-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
