# Generated by Django 4.1.3 on 2022-11-22 20:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0005_conversation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('user', 'to')},
        ),
    ]
