# Generated by Django 4.1.3 on 2022-11-23 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_alter_conversation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
    ]
